// tests/integrated-keyword-inputs.test.ts

import assert from "assert";
import { FormValidator } from "../lib/form-validator";
import { KeywordStudioEngine, GroundingInputContext } from "../lib/keyword-studio-engine";

export async function runIntegratedKeywordInputsTests() {
  console.log("\n============================================================");
  console.log("🎯 RUNNING INTEGRATED SEO & GEO DUAL-INPUT KEYWORDS TEST SUITE");
  console.log("============================================================\n");

  // -------------------------------------------------------------
  // TEST 1: CSV Parsing, Whitespace Trimming & Duplicate Detection
  // -------------------------------------------------------------
  console.log("--> [1/5] Testing CSV Parsing, Whitespace Trimming & Duplicate Detection...");

  const rawCsv = "  ai deal flow, b2b revops automation , pipeline velocity , AI Deal Flow, sales intelligence, b2b revops automation , enterprise sdr ";
  const parsed = FormValidator.parseCsvKeywords(rawCsv);

  assert.strictEqual(parsed.isValid, true, "CSV input successfully parsed");
  assert.strictEqual(parsed.keywords.length, 5, "Deduplicated into 5 unique keywords");
  assert.deepStrictEqual(parsed.keywords, [
    "ai deal flow",
    "b2b revops automation",
    "pipeline velocity",
    "sales intelligence",
    "enterprise sdr"
  ]);

  assert.strictEqual(parsed.duplicates.length, 2, "Detected 2 duplicate keyword entries");
  assert.ok(parsed.duplicates.map(d => d.toLowerCase()).includes("ai deal flow"));
  assert.ok(parsed.duplicates.map(d => d.toLowerCase()).includes("b2b revops automation"));

  console.log(`  ✅ CSV parsed: ${parsed.keywords.length} unique terms, ${parsed.duplicates.length} duplicates automatically merged`);

  // -------------------------------------------------------------
  // TEST 2: Invalid Token Handling & Error Reporting in CSV
  // -------------------------------------------------------------
  console.log("--> [2/5] Testing Invalid Keyword Detection in CSV String...");

  const invalidCsv = "valid keyword, a, ok term, bad<script>, another term";
  const invalidParsed = FormValidator.parseCsvKeywords(invalidCsv);

  assert.strictEqual(invalidParsed.isValid, false, "Marked as invalid due to token errors");
  assert.strictEqual(invalidParsed.invalidTokens.length, 2, "Detected 2 invalid tokens");
  assert.ok(invalidParsed.invalidTokens.includes("a"), "Detected too-short token 'a'");
  assert.ok(invalidParsed.invalidTokens.includes("bad<script>"), "Detected token with script tags");
  assert.ok(invalidParsed.errorMessage?.includes("failed validation"), "Actionable error message generated");

  console.log("  ✅ CSV validation successfully rejected malformed tokens with actionable error message");

  // -------------------------------------------------------------
  // TEST 3: Auto-Generation from ICP, Niche, Location & Content Objectives
  // -------------------------------------------------------------
  console.log("--> [3/5] Testing Auto-Generation Grounded in ICP, Niche, Location & Objectives...");

  const context: GroundingInputContext = {
    customerName: "CloudScale RevOps",
    industry: "Enterprise B2B SaaS",
    customerProfile: {
      companyName: "CloudScale RevOps",
      targetAudience: "VPs of Sales & RevOps Leaders",
      businessGoals: "Triple pipeline conversion rates with autonomous outreach",
      geographicMarkets: "North America & UK",
      companyInformation: { industry: "Enterprise B2B SaaS", websiteUrl: "https://cloudscale.ai" }
    },
    categoryTitle: "Outreach Tactics",
    subTypeTitle: "Cold Email Sequence",
    formValues: {
      targetPersona: "VPs of Sales & RevOps Leaders",
      valueProposition: "Triple pipeline conversion rates with autonomous outreach",
      primaryKeyword: "Autonomous Sales Pipeline"
    }
  };

  const autoGeneratedSet = KeywordStudioEngine.extractGroundedKeywords(context);

  assert.ok(autoGeneratedSet.seoKeywords.length >= 6, "Auto-generated SEO keywords populated");
  assert.ok(autoGeneratedSet.geoKeywords.length >= 5, "Auto-generated GEO citations populated");

  // Verify keywords incorporate ICP and location parameters
  const allSeoText = autoGeneratedSet.seoKeywords.map(k => k.keyword.toLowerCase()).join(" ");
  assert.ok(allSeoText.includes("enterprise b2b saas") || allSeoText.includes("autonomous sales pipeline"), "Incorporated niche and primary objective");

  console.log("  ✅ Auto-generated keywords dynamically grounded in ICP, Niche, Location & Objectives");

  // -------------------------------------------------------------
  // TEST 4: Custom Keyword Set Construction from Manual Mode
  // -------------------------------------------------------------
  console.log("--> [4/5] Testing Custom Keyword Set Generation from Manual Mode...");

  const customKeywords = ["autonomous lead qualification", "revops pipeline intelligence", "enterprise sdr platform"];
  const customSet = KeywordStudioEngine.createFromCustomKeywords(customKeywords, context);

  assert.strictEqual(customSet.seoKeywords.length, 3, "Created 3 custom SEO keyword items");
  assert.strictEqual(customSet.seoKeywords[0].keyword, "autonomous lead qualification");
  assert.ok(customSet.geoKeywords.length > 0, "Created default GEO citation triggers for custom terms");

  console.log("  ✅ Custom keyword set synthesized with SEO intent classifications and GEO citations");

  // -------------------------------------------------------------
  // TEST 5: Pipeline Deliverable Incorporation of Selected Keywords
  // -------------------------------------------------------------
  console.log("--> [5/5] Testing Deliverable Incorporation of Selected Custom Keywords...");

  const deliverableHtml = KeywordStudioEngine.buildSemanticHtmlDeliverable({
    categoryTitle: "Written Content",
    subTypeTitle: "SEO Optimized Blog Post",
    badge: "SEO-1",
    customerName: "CloudScale RevOps",
    formValues: context.formValues!,
    keywordSet: customSet,
    customerProfile: context.customerProfile
  });

  // Verify all custom keywords are embedded in the generated HTML
  for (const kw of customKeywords) {
    assert.ok(deliverableHtml.includes(kw), `Custom keyword '${kw}' incorporated in HTML deliverable`);
  }

  assert.ok(deliverableHtml.includes("Embedded Optimization Target Matrix"), "Deliverable includes SEO/GEO target matrix");
  console.log("  ✅ Selected keywords successfully incorporated into semantic HTML deliverable output");

  console.log("\n============================================================");
  console.log("🎉 ALL INTEGRATED KEYWORD INPUT TESTS PASSED (5/5)!");
  console.log("============================================================\n");
}

if (require.main === module) {
  runIntegratedKeywordInputsTests().catch(err => {
    console.error("Test execution failed:", err);
    process.exit(1);
  });
}
